INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());
INSERT INTO  tb_category(name, created_At ) VALUES ('Notebooks', NOW());
INSERT INTO  tb_category(name,created_At ) VALUES ('Books', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO  tb_category(name, created_At) VALUES ('Cards', NOW());